language: node_js
node_js:
  - '8'
before_script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: JeSs4jI5bHUSPO/+Y5sdhAWT+jfPGiwK3jkrzXhO6levY29YYEKA+tbBJXFwd5g360kxCdMmX/kYynZjvlYUSChsjBnP8+58Zj5WxuM5tbS3uy1TJ0FTNRnZa5AkLjxDg0rhzQ9J96KdDO2CPYbneR+9hYsJKmOtBFqJpOOTgKvqaqr4NsIhcM4etcLBLBPQlfCkUfZm6hN8KyMxFvS67D9V3gwkmS/QtxVVq/ZtcyEQSq4sV58t99tKw35Gsm6qfKXCgrkmVW6JJfPkx/PA2zx6CsGY6GplUJpOmjIF0UziHEdjoc3ln72Ub9VCppmWZ1APySY4tmxqzZh7m5MdpJFJnBPviJkjEJTlXjoCoHT7nd0XL7pJeRgsh+dlukBzrNS5d0/O2xG2XPbfozWr+AI0JZl5LpaIOrT++eRyyRJiPL9eemIVuYliOJFPKYVkxvxm4S+bs/uxY1due3jDIByR62XnW33/mXycKzL7wl277WLrtc7Hhq2aljhaA4YdcU2sKOgG/UQ3xJ9K88TOGoYkUn7Wht09M+5hezXdNHozrNNgUlDXFE6nQj9qbctAujtOQhNWk8bBbThKhoiqE/sNJV9eta4JTuP9DRJ4dnVMbIEtZl0yu0ILa/qEZSWqxS+x2fdNkSuY0SDudSIYbsHEyO/DcOW9Nt+u340mhS8=
  app: matheuslbarros-resume
  skip_cleanup: true
